
#ifndef constants_h
#define constants_h

#define LOOP_WAITING 500

#define MENU_SEPARATOR " -> "

//COMMON
#define MAX_ANALOG_WRITE 255

//STRINGS
#define WELCOME_TIME 2200
#define WELCOME_STRING_1 "ONYBOT: ROBOTICS"
#define WELCOME_STRING_2 "& CONSTRUCTIVISM"


#define MENU_STRING_1 "MENU"
#define MAIN_MENU_PROGRAM "PROGRAMAR"
#define MAIN_MENU_VIEW "VER ORDENES"
#define MAIN_MENU_DELETE "BORRAR ORDENES"
#define MAIN_MENU_RUN "EJECUTAR"
#define MAIN_MENU_VERSION "VERSION"

const String MAIN_MENU_STRING_2[] PROGMEM = {
	MAIN_MENU_PROGRAM,
	MAIN_MENU_VIEW,
	MAIN_MENU_RUN,
	MAIN_MENU_DELETE,
	MAIN_MENU_VERSION
};


#define PROGRAM_WAIT 1000 //time storing command
#define PROGRAM_WAIT_STRING_1 "ALMACENANDO..."
#define PROGRAM_STRING_1 "SELEC ORDEN"
#define PROGRAM_MENU_FORWARD "ADELANTE"
#define PROGRAM_MENU_REAR "ATRAS"
#define PROGRAM_MENU_LEFT "IZQUIERDA"
#define PROGRAM_MENU_RIGHT "DERECHA"

const String PROGRAM_MENU_STRING_2[] PROGMEM = {
	PROGRAM_MENU_FORWARD,
	PROGRAM_MENU_LEFT,
	PROGRAM_MENU_RIGHT,
	PROGRAM_MENU_REAR
};


#define VIEW_STRING_1 "ALMACENADO"
#define VIEW_STRING_EMPTY "------ "

#define DELETE_STRING_1 "BORRANDO"
#define DELETE_STRING_2 "ORDENES"
#define DELETE_TIME 1500


#define VERSION_STRING_1 "ONYBOT 0.0.1"
#define VERSION_STRING_2 "www.onytes.com"
#define VERSION_TIME 5000 //time showing version info


#define RUN_STRING_1 "EJECUTANDO"
#define RUN_STRING_2 "ORDEN"
#define COMMAND_TEST_DELAY 1000
#define RUN_SEPARATOR " - "
//LCD

#define LCD_CHARS 16
#define LCD_LINES 2
#define LCD_CTRL_LIGHT_PIN 10
#define LCD_LIGHT_MIN 0
#define LCD_LIGHT_MAX MAX_ANALOG_WRITE
#define DEFAULT_LCD_LIGHT LCD_LIGHT_MAX/30
#define LCD_LIGHT_TIME 2000
#define LCD_AUTOMATIC_LIGHT false

#endif