
#ifndef constants_h
#define constants_h

#define LOOP_WAITING 500

//COMMON
#define MAX_ANALOG_WRITE 255

//STRINGS
#define WELCOME_TIME 100
#define WELCOME_STRING_1 "ONYBOT: ROBOTICS"
#define WELCOME_STRING_2 "& CONSTRUCTIVISM"

#define MENU_STRING_1 "MENU"
#define MENU_PROGRAM "PROGRAMAR"
#define MENU_RUN "EJECUTAR"
#define MENU_VERSION "VERSION"
const String MENU_STRING_2[] PROGMEM = {MENU_PROGRAM, MENU_RUN, MENU_VERSION};


//LCD

#define LCD_CHARS 16
#define LCD_LINES 2
#define LCD_CTRL_LIGHT  10
#define DEFAULT_LCD_LIGHT MAX_ANALOG_WRITE/10


#endif